language: php

sudo: false

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
    include:
        - php: 7.3
          env: PHPLINT=1 PHPSNIFF=1 PHPUNIT=1
        - php: 7.2
          env: PHPLINT=1
        - php: 7.1
          env: PHPLINT=1
        - php: 7.0
          env: PHPLINT=1
        - php: 5.6
          env: PHPLINT=1

cache:
    directories:
        - $HOME/.composer/cache/files

before_script:
    - composer install --no-interaction --prefer-dist

script:
    - if [[ "$PHPLINT" == "1" ]]; then composer lint; fi
    - if [[ "$PHPUNIT" == "1" ]]; then composer test; fi
    - if [[ "$PHPSNIFF" == "1" ]]; then composer sniff; fi
